version: "3.3"

services:
  db:
    container_name: psql-club-manager-db
    image: postgres:16.3
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DATABASE=club_manager
    ports:
      - '5432:5432'
    volumes: 
      - club_manager_db_data:/var/lib/postgresql/data
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    command: ["sh", "-c", "docker-entrypoint.sh postgres & ./docker-entrypoint-initdb.d/init-db.sh"]
volumes:
  club_manager_db_data:
    driver: local